import streamlit as st
import pandas as pd
import os

st.set_page_config(
    page_title="Canada Trade Dashboard",
    layout="wide"
)

st.title("🇨🇦 Canada Trade Dashboard")

DATA_PATH = "data_processed/canada_trade_full.csv.gz"


@st.cache_data
def load_data():
    """
    Load dataset generated by the pipeline
    """
    return pd.read_csv(
        DATA_PATH,
        compression="gzip",
        low_memory=False
    )


# Check if dataset exists
if not os.path.exists(DATA_PATH):

    st.warning("Dataset not found. Generating dataset...")

    try:
        import subprocess

        subprocess.run(["python", "src/download_data.py"], check=True)
        subprocess.run(["python", "src/process_data.py"], check=True)

    except Exception as e:
        st.error("Dataset generation failed.")
        st.write(e)
        st.stop()


try:

    df = load_data()

    st.success("Dataset loaded successfully")

    # ---------------------------
    # Dataset overview
    # ---------------------------

    st.subheader("Dataset Overview")

    col1, col2, col3 = st.columns(3)

    col1.metric("Rows", f"{len(df):,}")
    col2.metric("Columns", len(df.columns))
    col3.metric("Trade Types", df["trade_type"].nunique())

    # ---------------------------
    # Preview
    # ---------------------------

    st.subheader("Dataset Preview")

    st.dataframe(df.head(20), use_container_width=True)

    # ---------------------------
    # Numeric analysis
    # ---------------------------

    numeric_cols = df.select_dtypes(include=["number"]).columns

    if len(numeric_cols) > 0:

        st.subheader("Trade Values (sample)")

        sample = df[numeric_cols[0]].head(100)

        st.bar_chart(sample)

    # ---------------------------
    # Trade type distribution
    # ---------------------------

    if "trade_type" in df.columns:

        st.subheader("Import vs Export")

        trade_counts = df["trade_type"].value_counts()

        st.bar_chart(trade_counts)

except Exception as e:

    st.error("Failed to load dataset")

    st.write(e)
